### ISSUE TITLE
Fehlermeldung beim Drucken/PDF erstellen

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#1031]
Beim Erstellen einer PDF (z.B. Statik -> Nicht zugeordnete Journale) erscheint folgende Fehlermeldung. Die PDF kann zwar trotzdem erstellt werden, die Fehlermeldung sollte aber trotzdem abgefangen/verhindert werden.

```
Nov. 26, 2021 8:25:33 AM org.apache.fop.apps.FOUserAgent processEvent
WARNUNG: The following feature isn't implemented by Apache FOP, yet: table-layout="auto" (on fo:table) (Keine Kontextinformationen verfügbar)
Nov. 26, 2021 8:25:33 AM org.apache.fop.apps.FOUserAgent processEvent
SCHWERWIEGEND: Invalid property value encountered in font="Humanist 521 BT": org.apache.fop.fo.expr.PropertyException: No conversion defined Humanist; property:'font' (Keine Kontextinformationen verfügbar)
org.apache.fop.fo.expr.PropertyException: No conversion defined Humanist; property:'font'
	at org.apache.fop.fo.properties.PropertyMaker.make(PropertyMaker.java:446)
	at org.apache.fop.fo.properties.FontSizePropertyMaker.make(FontSizePropertyMaker.java:55)
	at org.apache.fop.fo.properties.FontShorthandProperty$Maker.make(FontShorthandProperty.java:137)
	at org.apache.fop.fo.PropertyList.convertAttributeToProperty(PropertyList.java:413)
	at org.apache.fop.fo.PropertyList.addAttributeToList(PropertyList.java:258)
	at org.apache.fop.fo.PropertyList.addAttributesToList(PropertyList.java:299)
	at org.apache.fop.fo.FObj.processNode(FObj.java:122)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.startElement(FOTreeBuilder.java:280)
	at org.apache.fop.fo.FOTreeBuilder.startElement(FOTreeBuilder.java:175)
	at java.xml/com.sun.org.apache.xml.internal.serializer.ToXMLSAXHandler.closeStartTag(ToXMLSAXHandler.java:206)
	at java.xml/com.sun.org.apache.xml.internal.serializer.ToSAXHandler.flushPending(ToSAXHandler.java:250)
	at java.xml/com.sun.org.apache.xml.internal.serializer.ToXMLSAXHandler.endElement(ToXMLSAXHandler.java:245)
	at java.xml/com.sun.org.apache.xml.internal.serializer.ToXMLSAXHandler.endElement(ToXMLSAXHandler.java:557)
	at jdk.translet/die.verwandlung.NotAssignedJournalsStatistic_de_DE.template$dot$7()
	at jdk.translet/die.verwandlung.NotAssignedJournalsStatistic_de_DE.applyTemplates()
	at jdk.translet/die.verwandlung.NotAssignedJournalsStatistic_de_DE.applyTemplates()
	at jdk.translet/die.verwandlung.NotAssignedJournalsStatistic_de_DE.transform()
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.runtime.AbstractTranslet.transform(AbstractTranslet.java:624)
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:790)
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:383)
	at aero.minova.rcp.rcp.util.PDFGenerator.createPdfFile(PDFGenerator.java:55)
	at aero.minova.rcp.rcp.util.PrintUtil.generatePDF(PrintUtil.java:156)
	at aero.minova.rcp.rcp.util.PrintUtil.lambda$1(PrintUtil.java:58)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4262)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3885)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1041)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:168)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**Comment by wis36** [comment]
Das haben wir im Stand 10/11 auch bei fast jedem Druckformular.
Nutzt ihr auch FOP 1.1 oder eine neuere Version?

Wenn man den STRICT-Modus einstellt, können viele Dokumente nicht mehr erzeugt werden. Man müsste also viele Druckformulare korrigieren. Deswegen hatten wir es bisher nicht gemacht.
