### ISSUE TITLE
Fehlermeldung von SQL-Prozedur wird nicht richtig verarbeitet?

### ISSUE THREAD

**Issue by wis36** [minova-afis/aero.minova.rcp#1186]
Ich weiß nicht genau, was hier das Problem ist:

![grafik](https://user-images.githubusercontent.com/20420949/161487926-5a6de07f-848e-4d0f-9978-d4650c816cfb.png)

Entweder ist der Fehlercode vorn abgeschnitten worden (müsste "msg.DateBeforeMonthlyClosing" sein) oder bei der Verarbeitung / Anzeige von Fehlern stimmt etwas nicht.

Außerdem kommt eine zusätzliche NPE.

Ich arbeite auf dem Branch `DONT_MERGE_no_transaktions`.

**Comment by wis36** [comment]
Also bei der Fehlermeldung scheint schon der CAS bzw. die Prozedur eine falsche Fehlermeldung zu senden:

```
!MESSAGE CAS Answer Call Procedure:
{"resultSet":{"name":"Error","columns":[{"name":"International Message","type":"STRING"}],"rows":[{"values":["s-sg.DateBeforeMonthlyClosing"]}],"returnErrorMessage":{"detailsMessage":"sg.DateBeforeMonthlyClosing","cause":"aero.minova.core.application.system.domain.ProcedureException: com.microsoft.sqlserver.jdbc.SQLServerException: sg.DateBeforeMonthlyClosing","...
```

**Comment by wis36** [comment]
Die Original-Prozedur `spUpdateWorkingTime` wirft aber den richtigen Fehler.

**Comment by wis36** [comment]
Die NPE findet man so im Log:

```
!ENTRY org.eclipse.e4.ui.workbench 4 0 2022-04-04 08:42:29.852
!MESSAGE Internal Error
!STACK 0
java.lang.NullPointerException
	at aero.minova.rcp.rcp.util.WFCDetailCASRequestsUtil.checkNewEntryInsertUpdate(WFCDetailCASRequestsUtil.java:562)
	at aero.minova.rcp.rcp.util.WFCDetailCASRequestsUtil.lambda$5(WFCDetailCASRequestsUtil.java:537)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4029)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3629)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.jface.dialogs.MessageDialog.open(MessageDialog.java:394)
	at org.eclipse.jface.dialogs.MessageDialog.openError(MessageDialog.java:480)
	at aero.minova.rcp.rcp.util.WFCDetailCASRequestsUtil.showErrorMessage(WFCDetailCASRequestsUtil.java:659)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4029)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3629)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1041)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:168)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**Comment by janiak-minova** [comment]
Das Problem entsteht wahrscheinlich aus einer Kombination einer alten Version des CAS und den kurzfristig ausgebauten Transaktionen.

Sobald unsere Stundenerfassung auf den neusten Stand gebracht wird schauen wir nochmal, ob der Fehler noch auftritt.

**Comment by janiak-minova** [comment]
Inzwischen können wir eine aktuelle Version der Stundenerfassung nutzen. Ich habe es einmal ausprobiert, wie man sieht, wird die Fehlermeldung korrekt übersetzt dargestellt:

<img width="568" alt="Bildschirmfoto 2022-12-02 um 15 35 59" src="https://user-images.githubusercontent.com/77741125/205316888-f0b18c86-5ed2-4c21-a757-36f7e1bc7b3c.png">
