### ISSUE TITLE
Radioboxen unter Windows lassen sich nicht auswählen

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#1296]
Radioboxen unter Windows lassen sich nicht auswählen. Aufgefallen ist es in der Maske Prüfung des SAM.

**Comment by janiak-minova** [comment]
!ENTRY org.eclipse.e4.ui.workbench 4 0 2022-07-07 11:12:53.057
!MESSAGE Internal Error
!STACK 0
java.lang.NullPointerException
    at aero.minova.rcp.rcp.accessor.AbstractValueAccessor$1.focusLost(AbstractValueAccessor.java:51)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:147)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4237)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1084)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1065)
    at org.eclipse.swt.widgets.Control.sendFocusEvent(Control.java:2949)
    at org.eclipse.swt.widgets.Widget.wmKillFocus(Widget.java:1872)
    at org.eclipse.swt.widgets.Control.WM_KILLFOCUS(Control.java:5176)
    at org.eclipse.swt.widgets.Button.WM_KILLFOCUS(Button.java:1158)
    at org.eclipse.swt.widgets.Control.windowProc(Control.java:4787)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:4966)
    at org.eclipse.swt.internal.win32.OS.BringWindowToTop(Native Method)
    at org.eclipse.swt.widgets.Decorations.bringToTop(Decorations.java:211)
    at org.eclipse.swt.widgets.Shell.open(Shell.java:1269)
    at org.eclipse.jface.window.Window.open(Window.java:795)
    at org.eclipse.jface.dialogs.ErrorDialog.open(ErrorDialog.java:349)
    at org.eclipse.e4.ui.internal.workbench.swt.WorkbenchStatusReporter.openDialog(WorkbenchStatusReporter.java:127)
    at org.eclipse.e4.ui.internal.workbench.swt.WorkbenchStatusReporter.report(WorkbenchStatusReporter.java:65)
    at org.eclipse.e4.core.services.statusreporter.StatusReporter.show(StatusReporter.java:135)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5$1.eventLoopException(PartRenderingEngine.java:1127)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.handle(PartRenderingEngine.java:1170)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.lambda$1(PartRenderingEngine.java:1145)
    at org.eclipse.swt.internal.ExceptionStash.stash(ExceptionStash.java:63)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4237)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1084)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1065)
    at org.eclipse.swt.widgets.Control.sendFocusEvent(Control.java:2949)
    at org.eclipse.swt.widgets.Widget.wmSetFocus(Widget.java:2283)
    at org.eclipse.swt.widgets.Control.WM_SETFOCUS(Control.java:5434)
    at org.eclipse.swt.widgets.Button.WM_SETFOCUS(Button.java:1189)
    at org.eclipse.swt.widgets.Control.windowProc(Control.java:4825)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:4958)
    at org.eclipse.swt.internal.win32.OS.CallWindowProc(Native Method)
    at org.eclipse.swt.widgets.Button.callWindowProc(Button.java:256)
    at org.eclipse.swt.widgets.Widget.wmLButtonDown(Widget.java:1942)
    at org.eclipse.swt.widgets.Control.WM_LBUTTONDOWN(Control.java:5184)
    at org.eclipse.swt.widgets.Button.WM_LBUTTONDOWN(Button.java:1168)
    at org.eclipse.swt.widgets.Control.windowProc(Control.java:4789)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:4966)
    at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3624)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1041)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
    at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:168)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

!ENTRY org.eclipse.e4.ui.workbench 4 0 2022-07-07 11:12:53.057
!MESSAGE Internal Error
!STACK 0
java.lang.NullPointerException
    at aero.minova.rcp.rcp.accessor.AbstractValueAccessor$1.focusLost(AbstractValueAccessor.java:51)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:147)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4237)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1084)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1065)
    at org.eclipse.swt.widgets.Control.sendFocusEvent(Control.java:2949)
    at org.eclipse.swt.widgets.Widget.wmKillFocus(Widget.java:1872)
    at org.eclipse.swt.widgets.Control.WM_KILLFOCUS(Control.java:5176)
    at org.eclipse.swt.widgets.Button.WM_KILLFOCUS(Button.java:1158)
    at org.eclipse.swt.widgets.Control.windowProc(Control.java:4787)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:4966)
    at org.eclipse.swt.internal.win32.OS.BringWindowToTop(Native Method)
    at org.eclipse.swt.widgets.Decorations.bringToTop(Decorations.java:211)
    at org.eclipse.swt.widgets.Shell.open(Shell.java:1269)
    at org.eclipse.jface.window.Window.open(Window.java:795)
    at org.eclipse.jface.dialogs.ErrorDialog.open(ErrorDialog.java:349)
    at org.eclipse.e4.ui.internal.workbench.swt.WorkbenchStatusReporter.openDialog(WorkbenchStatusReporter.java:127)
    at org.eclipse.e4.ui.internal.workbench.swt.WorkbenchStatusReporter.report(WorkbenchStatusReporter.java:65)
    at org.eclipse.e4.core.services.statusreporter.StatusReporter.show(StatusReporter.java:135)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5$1.eventLoopException(PartRenderingEngine.java:1127)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.handle(PartRenderingEngine.java:1170)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.lambda$1(PartRenderingEngine.java:1145)
    at org.eclipse.swt.internal.ExceptionStash.stash(ExceptionStash.java:63)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4237)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1084)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1065)
    at org.eclipse.swt.widgets.Control.sendFocusEvent(Control.java:2949)
    at org.eclipse.swt.widgets.Widget.wmSetFocus(Widget.java:2283)
    at org.eclipse.swt.widgets.Control.WM_SETFOCUS(Control.java:5434)
    at org.eclipse.swt.widgets.Button.WM_SETFOCUS(Button.java:1189)
    at org.eclipse.swt.widgets.Control.windowProc(Control.java:4825)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:4958)
    at org.eclipse.swt.internal.win32.OS.CallWindowProc(Native Method)
    at org.eclipse.swt.widgets.Button.callWindowProc(Button.java:256)
    at org.eclipse.swt.widgets.Widget.wmLButtonDown(Widget.java:1942)
    at org.eclipse.swt.widgets.Control.WM_LBUTTONDOWN(Control.java:5184)
    at org.eclipse.swt.widgets.Button.WM_LBUTTONDOWN(Button.java:1168)
    at org.eclipse.swt.widgets.Control.windowProc(Control.java:4789)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:4966)
    at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3624)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1041)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
    at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:168)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
