### ISSUE TITLE
Fehler beim 2. Öffnen des Wizards

### ISSUE THREAD

**Issue by wis36** [minova-afis/aero.minova.rcp#1478]
Aufgefallen in WFC-Stundenerfassung:

1. Wizard "Arbeitszeit füllen" öffnen
2. Ausfüllen, speichern
3. Wizard erneut öffnen - funktioniert nicht, es kommt die Exception:

```
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4907)
	at org.eclipse.swt.SWT.error(SWT.java:4822)
	at org.eclipse.swt.SWT.error(SWT.java:4793)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:445)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:364)
	at org.eclipse.swt.widgets.Control.setToolTipText(Control.java:3870)
	at aero.minova.rcp.rcp.accessor.AbstractValueAccessor.setTooltip(AbstractValueAccessor.java:170)
	at aero.minova.rcp.model.form.MField.setTooltip(MField.java:544)
	at aero.minova.rcp.model.form.MTextField.isValid(MTextField.java:23)
	at aero.minova.rcp.model.form.MDetail.allFieldsAndGridsValid(MDetail.java:202)
	at aero.minova.rcp.rcp.widgets.MinovaWizardPage.valueChange(MinovaWizardPage.java:308)
	at aero.minova.workingtime.wizard.PeriodPage.valueChange(PeriodPage.java:95)
	at aero.minova.rcp.model.form.MField.fire(MField.java:117)
	at aero.minova.rcp.model.form.MField.setValue(MField.java:133)
	at aero.minova.workingtime.wizard.PeriodPage.createControl(PeriodPage.java:50)
	at org.eclipse.jface.wizard.Wizard.createPageControls(Wizard.java:178)
	at org.eclipse.jface.wizard.WizardDialog.createPageControls(WizardDialog.java:743)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:635)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1094)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at aero.minova.rcp.rcp.handlers.DynamicButtonHandler.execute(DynamicButtonHandler.java:59)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:195)
	at aero.minova.rcp.rcp.parts.WFCDetailPart$3.widgetSelected(WFCDetailPart.java:775)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4060)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3632)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:168)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

!ENTRY aero.minova.rcp.dataservice 4 0 2023-05-02 08:32:05.604
!MESSAGE Plugin für Klasse aero.minova.workingtime.wizard.FillWorkingtimeWizard konnte nicht geladen werden
```

**Comment by janiak-minova** [comment]
Ich konnte das Verhalten weder unter Mac noch Windows nachstellen.

Startest du aus Eclipse? Wenn ja, lädst du den Helper auch aus eclipse (siehe Screenshot)?
Wenn ja, ggf. mal die Option deaktivieren, oder die aktuellste Version vom aero.minova.workingtime pullen.
<img width="787" alt="image" src="https://user-images.githubusercontent.com/77741125/235604294-b0668b5d-b41f-4af3-a168-4fc555e1a85b.png">

**Comment by janiak-minova** [comment]
Oh, sorry, den Schritt 2 habe ich gekonnt übersprungen. 
Wenn man es ausfüllt, geht es tatsächlich nicht mehr ein zweites Mal auf.

Ich schaue es an.

**Comment by janiak-minova** [comment]
Ist in [Version 12.9.2](https://github.com/minova-afis/aero.minova.rcp/releases/tag/v12.9.2) gelöst.
