### ISSUE TITLE
WFC startet nicht aus Eclipse

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#1554]
Beim Versuch, das WFC aus Eclipse zu starten erscheint folgender Fehler

```
java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons:
	Can't load /Users/erlanger/eclipse/committers-2023-09/Eclipse.app/Contents/MacOS/freetables-workspace/.metadata/.plugins/org.eclipse.pde.core/aero.minova.rcp.rcp.product/org.eclipse.osgi/137/0/.cp/libswt-cocoa-4948r9.jnilib
	no swt-cocoa in java.library.path: /Users/erlanger/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	no swt in java.library.path: /Users/erlanger/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	Can't load library: /Users/erlanger/.swt/lib/macosx/x86_64/libswt-cocoa-4948r9.jnilib
	Can't load library: /Users/erlanger/.swt/lib/macosx/x86_64/libswt-cocoa.jnilib
	Can't load library: /Users/erlanger/.swt/lib/macosx/x86_64/libswt.jnilib
	Can't load library: /Users/erlanger/.swt/lib/macosx/x86_64/libswt-cocoa-4948r9.jnilib
 
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:348)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:257)
	at org.eclipse.swt.internal.C.<clinit>(C.java:19)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:108)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
An error has occurred. See the log file
/Users/erlanger/eclipse/committers-2023-09/Eclipse.app/Contents/MacOS/freetables-workspace/.metadata/.plugins/org.eclipse.pde.core/aero.minova.rcp.rcp.product/1708091714321.log.
```

**Comment by janiak-minova** [comment]
Lösung:
- [Eclipse Version 2024-03](https://www.eclipse.org/downloads/packages/release/2024-03/m2) benutzen (für macOS mit M2 Prozessor AArch64)
- ggf. Ordner `/Users/<username>/.swt/` löschen
- Anwendung starten
   - `Synchronize` und `Launch an Eclipse application in Debug mode` (siehe Screenshot)
   - Anwendung startet mit Fehler
   - In der Debug configuration die Location entfernen (siehe Screenshot)
   - Unter `Plug-ins` einstellen (siehe Screenshot):
       - Launch with: `Plug-ins selected below`
       - `aero.minova.rcp.workspace` per Hand auswählen
       - Auf `Select Required` klicken
       - Es sollten da stehen: `161 out of 367 selected`   

<img width="1721" alt="image" src="https://github.com/minova-afis/aero.minova.rcp/assets/77741125/83dde3d3-7271-469d-8afe-498d6007f382">

<img width="930" alt="image" src="https://github.com/minova-afis/aero.minova.rcp/assets/77741125/620dd2a1-82c3-4019-845f-dd0790fdc3d5">

<img width="934" alt="image" src="https://github.com/minova-afis/aero.minova.rcp/assets/77741125/9af8a685-809d-418e-b3e3-cda4d83107c3">

Damit sollte die Anwendung ohne Fehler starten.
