### ISSUE TITLE
Tests auf Github laufen nicht durch

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#1587]
Die Tests auf Github laufen nicht durch, weil keine Verbindung zum publictest zustande kommen kann.
Wahrscheinlich liegt es an der neuen Firewall, @sebold-minova ist dran.

**Comment by janiak-minova** [comment]
An der Firewall liegt es nicht, es tritt ein anderer Fehler auf:

```
aero.minova.rcp.uitests.OpenStundenerfassungsUITest.filterIndex  Time elapsed: 9.343 s  <<< ERROR!
java.lang.LinkageError: loader constraint violation: loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @41ff37ab wants to load interface org.hamcrest.Matcher. A different interface with the same name was previously loaded by org.eclipse.osgi.internal.loader.EquinoxClassLoader @39b3dfeb. (org.hamcrest.Matcher is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @39b3dfeb, parent loader 'platform')
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.defineClass(ModuleClassLoader.java:283)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.defineClass(ClasspathManager.java:716)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:639)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:607)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:587)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:566)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:384)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:475)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:403)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
. . .
```
