### ISSUE TITLE
FillWorkingtimeWizard startet nicht

### ISSUE THREAD

**Issue by wis36** [minova-afis/aero.minova.rcp#637]
Dieser Wizard ist nur Teil der Stundenerfassung, also müsste das WFC auch ohne auskommen. Wenn ich auf den Button drücke, sollte entweder
* eine lesbare Fehlermeldung erscheinen
* oder das Modul vom CAS nachgeladen werden

Aktuell bekomme ich im Log:
java.lang.ClassNotFoundException: aero.minova.workingtime.wizard.FillWorkingtimeWizard cannot be found by aero.minova.rcp.rcp_12.0.21.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:519)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at aero.minova.rcp.rcp.handlers.DynamicButtonHandler.execute(DynamicButtonHandler.java:33)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:319)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:253)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:195)
	at aero.minova.rcp.rcp.parts.WFCDetailPart$1.widgetSelected(WFCDetailPart.java:276)
...

**Comment by janiak-minova** [comment]
Wurde die Anwendung über Eclipse gestartet oder die gebaute Anwendung?

**Comment by wis36** [comment]
über Eclipse

**Comment by janiak-minova** [comment]
Dann muss das Plugin erst per Hand importiert werden (aero.minova.workingtime.wizard).
Das Nachladen der nötigen Plugins vom Server ist noch nicht implementiert.

**Comment by wis36** [comment]
Achso, dann ist es kein Bug sondern ein noch fehlendes Feature 😉
Fehlt da von Seiten CAS noch was?

**Comment by weber-minova** [comment]
Das CAS kann noch keine Plugins nachladen

**Comment by janiak-minova** [comment]
Das Plugins Nachladen ist auch in #236 und #158 beschrieben.
