### ISSUE TITLE
Keine Tickets werden nicht mehr aufgelöst.

### ISSUE THREAD

**Issue by splitcells** [minova-afis/aero.minova.rcp#793]
Eine Ursache wahr nicht erkennbar.
Ein Neustart der Anwendung hat das Problem behoben.

Laut den Logs, war bei dem ersten Fehler, dass Problem, dass kein Ticket für eine Ticketnummer gefunden wurde.
Die darauffolgenden Fehler scheinen mit den ersten Fehler zu tu zu haben,
da die darauffolgenden CAS-Antworten rows hatten.

`	at aero.minova.rcp.rcp.util.WFCDetailCASRequestsUtil.checkFields(WFCDetailCASRequestsUtil.java:884)`:
An der betroffenen Stelle, sollte geloggt werden, was die selectedTable ist,
da diese nicht immer der Antwort vom CAS  entspricht.

![grafik](https://user-images.githubusercontent.com/7956931/129865597-3726258c-3ec2-494e-8061-2f8b4333478a.png)

Letzter Fehler im Log:
```
!ENTRY org.eclipse.e4.ui.workbench 1 0 2021-08-18 10:29:47.953
!MESSAGE CAS Answer Detail Data:
{"resultSet":{"metaData":{"limited":95,"page":1,"totalResults":95,"totalPages":1,"resultsLeft":0},"columns":[{"name":"KeyLong","type":"INTEGER"},{"name":"KeyText","type":"STRING"},{"name":"Description","type":"STRING"},{"name":"LastAction","type":"INTEGER"}],"rows":[{"values":["n-2","s-BP","s-BP - Achtung: Rechnungsadresse und MWST?","n-1"]},{"values":["n-8","s-FREV",null,"n-1"]},{"values":["n-10","s-HAL","s-Halter (Wil)","n-1"]},{"values":["n-22","s-MIN","s-MINOVA Information Services GmbH","n-1"]},{"values":["n-23","s-MINAG","s-MINOVA Information Systems GmbH","n-1"]},{"values":["n-24","s-OAS","s-Skytanking München","n-1"]},{"values":["n-26","s-OKCO","s-Coop Mineraloel AG","n-1"]},{"values":["n-30","s-ROTH",null,"n-1"]},{"values":["n-31","s-SCHAET","s-Schätzle AG (Luzern)","n-1"]},{"values":["n-34","s-TABEG",null,"n-1"]},{"values":["n-35","s-TAEG",null,"n-1"]},{"values":["n-36","s-TAM","s-TAM (Erfassung TTS+TTSWB in Englisch)","n-1"]},{"values":["n-40","s-OMV",null,"n-1"]},{"values":["n-49","s-TAA",null,"n-1"]},{"values":["n-56","s-SAW","s-Wilfried Saak","n-1"]},{"values":["n-58","s-TFE",null,"n-1"]},{"values":["n-67","s-THG","s-Gudrun Theuerer","n-1"]},{"values":["n-75","s-MAROL","s-MAROL Energie GmbH \u0026 Co. KG","n-1"]},{"values":["n-80","s-GKG",null,"n-1"]},{"values":["n-81","s-MOH","s-Morrison Heidi","n-1"]},{"values":["n-82","s-IPS","s-IPS Intoplane Service Pool","n-1"]},{"values":["n-83","s-GFS","s-Geneva Fuelling Services","n-1"]},{"values":["n-84","s-AFIS","s-AFIS","n-1"]},{"values":["n-86","s-CJG","s-CJG Business Development","n-1"]},{"values":["n-88","s-HOM","s-Hofmann Martin","n-1"]},{"values":["n-92","s-CRS","s-CRS  (Erfassung in Englisch)","n-1"]},{"values":["n-97","s-TAMAG","s-Tankanlagen Mellingen AG","n-1"]},{"values":["n-98","s-SKYVIE","s-Skytanking Vienna","n-1"]},{"values":["n-100","s-PSTOCK","s-PETROSTOCK","n-1"]},{"values":["n-104","s-TANQD","s-TanQuid Duisburg","n-1"]},{"values":["n-105","s-MANSR","s-Mansrich Ltd.","n-1"]},{"values":["n-106","s-TAR","s-TAR - Tankanlage Rümlang","n-1"]},{"values":["n-109","s-SHELLCH","s-Shell","n-1"]},{"values":["n-120","s-WUTH","s-Wuthrich","n-1"]},{"values":["n-123","s-PO","s-Petrol Ofisi","n-1"]},{"values":["n-124","s-SKYSTR","s-Skytanking Stuttgart","n-1"]},{"values":["n-126","s-SOGEP","s-SOGEP","n-1"]},{"values":["n-128","s-GOB","s-Gourlat","n-1"]},{"values":["n-129","s-PRAEG","s-PRAEG","n-1"]},{"values":["n-130","s-BENOIL","s-BENOIL","n-1"]},{"values":["n-135","s-RVS","s-Raiffeisenverband Salburg","n-1"]},{"values":["n-137","s-RUEK","s-RÜK (Erfassung in Englisch)","n-1"]},{"values":["n-138","s-UGAFCO","s-UGAFCO (English)","n-1"]},{"values":["n-141","s-AGROLA","s-AGROLA (immer Auftraggeber angeben!)","n-1"]},{"values":["n-145","s-HBG","s-Hydranten-Betriebs OHG","n-1"]},{"values":["n-146","s-ZOTZ","s-ZOTZ","n-1"]},{"values":["n-147","s-VARO","s-VARO -\u003e CREWB  in E / RA Marketing o. Tankstorage?","n-1"]},{"values":["n-152","s-WOELFL","s-Andreas Wölfl Transport GmbH","n-1"]},{"values":["n-153","s-SCHARNAGL","s-Scharnagl","n-1"]},{"values":["n-155","s-SUK","s-Schöpper \u0026 Knoll","n-1"]},{"values":["n-158","s-HUBER","s-Werner Huber GmbH","n-1"]},{"values":["n-160","s-HOYER","s-Hoyer","n-1"]},{"values":["n-164","s-WOLTER","s-Ewald Wolter GmbH","n-1"]},{"values":["n-166","s-SKYZRH","s-Skytanking Zürich","n-1"]},{"values":["n-171","s-WAHR","s-Fritz Wahr Energie GmbH \u0026 Co. KG","n-1"]},{"values":["n-177","s-PETRONAS","s-Petronas Heilbronn","n-1"]},{"values":["n-182","s-KLAESER","s-Klaeser","n-1"]},{"values":["n-193","s-ZUEGEL","s-Zügel GmbH \u0026 Co. KG","n-1"]},{"values":["n-197","s-TOTALD","s-Total Deutschland GmbH","n-1"]},{"values":["n-201","s-SKEL","s-SKELJUNGUR (Erfassung in Englisch)","n-1"]},{"values":["n-204","s-OELPOOL","s-OEL-POOL AG","n-1"]},{"values":["n-205","s-AIRTOTAL","s-AIR TOTAL (SUISSE) SA","n-1"]},{"values":["n-208","s-IUS","s-Irrgang \u0026 Schneider GmbH","n-1"]},{"values":["n-209","s-KASAG","s-KASAGTankbau","n-1"]},{"values":["n-210","s-PLOT","s-PETROLOT - Erfassung in Englisch","n-1"]},{"values":["n-211","s-VWG","s-V.W. Günther Mineralölhandelsgesellschaft mbH","n-1"]},{"values":["n-213","s-LDC",null,"n-1"]},{"values":["n-218","s-SCHWARZ","s-Schwarz GmbH Biberach","n-1"]},{"values":["n-221","s-SKYBRU","s-Skytanking Brüssel Erfassung in Englisch","n-1"]},{"values":["n-222","s-IMO2","s-In-Motion SA","n-1"]},{"values":["n-224","s-leuend","s-Leuendorff","n-1"]},{"values":["n-226","s-WIFELD","s-Wingenfeld Energie GmbH","n-1"]},{"values":["n-229","s-OILT","s-Oiltanking Deutschland WIKI beachten!","n-1"]},{"values":["n-230","s-IGA","s-IGA","n-1"]},{"values":["n-232","s-OBERTI","s-Oberti GmbH \u0026 Co. KG","n-1"]},{"values":["n-233","s-ADSA","s-AVIA Distribution SA ","n-1"]},{"values":["n-236","s-HHOPCO","s-Heathrow Hydrant Operating Company","n-1"]},{"values":["n-239","s-DOETSCH","s-Erich Doetsch GmbH","n-1"]},{"values":["n-240","s-HCP","s-hansaconsult projects DWC LLC","n-1"]},{"values":["n-241","s-SKY","s-Skytanking allgemein","n-1"]},{"values":["n-243","s-BADER","s-Bader Mineralölvertrieb","n-1"]},{"values":["n-244","s-VIA","s-VIA ENERGY GmbH","n-1"]},{"values":["n-246","s-STORZ","s-Conrad-Storz AG","n-1"]},{"values":["n-247","s-JUBIN","s-Jubin Freres SA","n-1"]},{"values":["n-248","s-KRIEGER","s-Krieger Nutzfahrzeuge AG","n-1"]},{"values":["n-250","s-SKYBRE","s-SKYBRE","n-1"]},{"values":["n-252","s-SKYBER","s-Skytanking Berlin","n-1"]},{"values":["n-255","s-SAILER","s-SAILER Mineralölhandel GmbH","n-1"]},{"values":["n-256","s-STEHLE","s-Katja Stehle","n-1"]},{"values":["n-257","s-SCHWARZH","s-Hanna Schwarz","n-1"]},{"values":["n-258","s-ENGELH","s-Winnie Engelhardt - Lokales Filmmarketing","n-1"]},{"values":["n-259","s-BIOSYNTEC","s-Biosyntec GmbH","n-1"]},{"values":["n-260","s-AGRAVIS","s-AGRAVIS Raiffeisen AG","n-1"]},{"values":["n-262","s-WALTHER","s-Erik Walther GmbH \u0026 Co. KG","n-1"]},{"values":["n-263","s-ETB","s-Energie Tankdienstgesellschaft Bremen mbH","n-1"]}]},"returnCode":0}

!ENTRY org.eclipse.e4.ui.workbench 4 0 2021-08-18 10:29:49.574
!MESSAGE Internal Error
!STACK 0
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at aero.minova.rcp.rcp.util.WFCDetailCASRequestsUtil.checkFields(WFCDetailCASRequestsUtil.java:884)
	at aero.minova.rcp.rcp.util.WFCDetailCASRequestsUtil.checkDirty(WFCDetailCASRequestsUtil.java:865)
	at aero.minova.rcp.rcp.parts.WFCDetailPart.checkDirtyFlag(WFCDetailPart.java:729)
	at aero.minova.rcp.rcp.parts.WFCDetailPart.valueChange(WFCDetailPart.java:724)
	at aero.minova.rcp.model.form.MField.fire(MField.java:103)
	at aero.minova.rcp.model.form.MField.setValue(MField.java:122)
	at aero.minova.rcp.rcp.accessor.LookupValueAccessor.setFocussed(LookupValueAccessor.java:122)
	at aero.minova.rcp.rcp.accessor.AbstractValueAccessor$1.focusLost(AbstractValueAccessor.java:38)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:147)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1067)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1048)
	at org.eclipse.swt.widgets.Control.sendFocusEvent(Control.java:2956)
	at org.eclipse.swt.widgets.Widget.wmKillFocus(Widget.java:1855)
	at org.eclipse.swt.widgets.Control.WM_KILLFOCUS(Control.java:5183)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4794)
	at org.eclipse.swt.widgets.Text.windowProc(Text.java:2681)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4938)
	at org.eclipse.swt.internal.win32.OS.PeekMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3621)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:168)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:654)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1462)
```

**Comment by splitcells** [comment]
```!ENTRY org.eclipse.e4.ui.workbench 1 0 2021-08-18 10:28:54.703
!MESSAGE CAS Answer Detail Data:
{"resultSet":{"name":"Ticket","columns":[{"name":"TicketKey","type":"INTEGER"},{"name":"OrderReceiver","type":"STRING"},{"name":"ServiceContract","type":"STRING"},{"name":"ServiceObject","type":"STRING"},{"name":"Service","type":"STRING"},{"name":"Description","type":"STRING"},{"name":"OrderReceiverKey","type":"INTEGER"},{"name":"ServiceContractKey","type":"INTEGER"},{"name":"ServiceObjectKey","type":"INTEGER"},{"name":"ServiceKey","type":"INTEGER"}],"rows":[]},"returnCode":1}

!ENTRY org.eclipse.e4.ui.workbench 4 0 2021-08-18 10:28:54.711
!MESSAGE Internal Error
!STACK 0
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at aero.minova.rcp.rcp.util.WFCDetailCASRequestsUtil.checkFields(WFCDetailCASRequestsUtil.java:884)
	at aero.minova.rcp.rcp.util.WFCDetailCASRequestsUtil.checkDirty(WFCDetailCASRequestsUtil.java:865)
	at aero.minova.rcp.rcp.parts.WFCDetailPart.checkDirtyFlag(WFCDetailPart.java:729)
	at aero.minova.rcp.rcp.parts.WFCDetailPart.valueChange(WFCDetailPart.java:724)
	at aero.minova.rcp.model.form.MField.fire(MField.java:103)
	at aero.minova.rcp.model.form.MField.setValue(MField.java:122)
	at aero.minova.rcp.rcp.accessor.LookupValueAccessor.setFocussed(LookupValueAccessor.java:122)
	at aero.minova.rcp.rcp.accessor.AbstractValueAccessor$1.focusLost(AbstractValueAccessor.java:38)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:147)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1067)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1048)
	at org.eclipse.swt.widgets.Control.sendFocusEvent(Control.java:2956)
	at org.eclipse.swt.widgets.Widget.wmKillFocus(Widget.java:1855)
	at org.eclipse.swt.widgets.Control.WM_KILLFOCUS(Control.java:5183)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4794)
	at org.eclipse.swt.widgets.Text.windowProc(Text.java:2681)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4938)
	at org.eclipse.swt.internal.win32.OS.SetFocus(Native Method)
	at org.eclipse.swt.widgets.Control.forceFocus(Control.java:1107)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.forceFocus(SWTPartRenderer.java:365)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.focusGui(PartRenderingEngine.java:796)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:764)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:679)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:674)
	at aero.minova.rcp.rcp.util.WFCDetailCASRequestsUtil.showErrorMessage(WFCDetailCASRequestsUtil.java:496)
	at aero.minova.rcp.rcp.util.WFCDetailCASRequestsUtil.lambda$22(WFCDetailCASRequestsUtil.java:638)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4001)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3629)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:168)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:654)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1462)
```

**Comment by janiak-minova** [comment]
Ist das gleiche Problem wie #761, wurde mit #778 behoben.
